const dummy = {
    "page": 1,
    "total_results": 20,
    "total_pages": 2,
    "results": [
        {
            "id": 1,
            "title": "The Witcher 3: Wild Hunt",
            "overview": "The Witcher 3: Wild Hunt is an action role-playing game set in an open world environment.",
            "original_title": "The Witcher 3: Wild Hunt",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdnb.artstation.com/p/assets/images/images/058/109/407/large/archita-nair-0640b32d-16b2-48f3-a9bf-6c709f25d4d1.jpg?1673401411",
            "popularity": 9.2,
            "vote_count": 1500,
            "vote_average": 9.3,
            "video": false,
            "poster_path": "https://cdnb.artstation.com/p/assets/images/images/058/109/407/large/archita-nair-0640b32d-16b2-48f3-a9bf-6c709f25d4d1.jpg?1673401411"
        },
        {
            "id": 2,
            "title": "Grand Theft Auto V",
            "overview": "Grand Theft Auto V is an action-adventure game played from either a first-person or third-person perspective.",
            "original_title": "Grand Theft Auto V",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/77/ce/46/77ce46aebb09e4189c5cdc045cdd948a.jpg",
            "popularity": 9.0,
            "vote_count": 1200,
            "vote_average": 8.8,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/77/ce/46/77ce46aebb09e4189c5cdc045cdd948a.jpg"
        },
        {
            "id": 3,
            "title": "The Legend of Zelda: Breath of the Wild",
            "overview": "The Legend of Zelda: Breath of the Wild is an action-adventure game developed and published by Nintendo.",
            "original_title": "The Legend of Zelda: Breath of the Wild",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdna.artstation.com/p/assets/images/images/038/897/974/large/lucas-barcelos-tucas-zeldinha3.jpg?1624379746",
            "popularity": 8.9,
            "vote_count": 1100,
            "vote_average": 9.5,
            "video": false,
            "poster_path": "https://cdna.artstation.com/p/assets/images/images/038/897/974/large/lucas-barcelos-tucas-zeldinha3.jpg?1624379746"
        },
        {
            "id": 4,
            "title": "Red Dead Redemption 2",
            "overview": "Red Dead Redemption 2 is an action-adventure game set in an open world environment.",
            "original_title": "Red Dead Redemption 2",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdna.artstation.com/p/assets/images/images/019/451/830/large/cesar-jaffar-picsart-07-19-04-44-01.jpg?1563543921",
            "popularity": 8.8,
            "vote_count": 1050,
            "vote_average": 9.2,
            "video": false,
            "poster_path": "https://cdna.artstation.com/p/assets/images/images/019/451/830/large/cesar-jaffar-picsart-07-19-04-44-01.jpg?1563543921"
        },
        {
            "id": 5,
            "title": "The Last of Us Part II",
            "overview": "The Last of Us Part II is an action-adventure game developed by Naughty Dog.",
            "original_title": "The Last of Us Part II",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://64.media.tumblr.com/09ba8aed8a54c7a866d9f872b5079ad2/6b9c31a0447201bd-c5/s1280x1920/cd303373296cd50536d5d1f0768077085a335b80.jpg",
            "popularity": 8.7,
            "vote_count": 1000,
            "vote_average": 9.4,
            "video": false,
            "poster_path": "https://64.media.tumblr.com/09ba8aed8a54c7a866d9f872b5079ad2/6b9c31a0447201bd-c5/s1280x1920/cd303373296cd50536d5d1f0768077085a335b80.jpg"
        },
        {
            "id": 6,
            "title": "God of War",
            "overview": "God of War is an action-adventure game developed by Santa Monica Studio.",
            "original_title": "God of War",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdnb.artstation.com/p/assets/images/images/047/043/733/large/hritik-dubariya-img-20211111-163856-355.jpg?1646633834",
            "popularity": 8.6,
            "vote_count": 950,
            "vote_average": 9.1,
            "video": false,
            "poster_path": "https://cdnb.artstation.com/p/assets/images/images/047/043/733/large/hritik-dubariya-img-20211111-163856-355.jpg?1646633834"
        },
        {
            "id": 7,
            "title": "Super Mario Odyssey",
            "overview": "Super Mario Odyssey is a platform game developed and published by Nintendo for the Nintendo Switch.",
            "original_title": "Super Mario Odyssey",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdn.europosters.eu/image/750webp/50045.webp",
            "popularity": 8.5,
            "vote_count": 900,
            "vote_average": 9.0,
            "video": false,
            "poster_path": "https://cdn.europosters.eu/image/750webp/50045.webp"
        },
        {
            "id": 8,
            "title": "Halo: Combat Evolved",
            "overview": "Halo: Combat Evolved is a first-person shooter game developed by Bungie.",
            "original_title": "Halo: Combat Evolved",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://wallpaperaccess.com/full/3244661.png",
            "popularity": 8.4,
            "vote_count": 850,
            "vote_average": 8.9,
            "video": false,
            "poster_path": "https://wallpaperaccess.com/full/3244661.png"
        },
        {
            "id": 9,
            "title": "Minecraft",
            "overview": "Minecraft is a sandbox video game developed by Mojang Studios.",
            "original_title": "Minecraft",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://wallpapercave.com/dwp1x/wp11667632.png",
            "popularity": 8.3,
            "vote_count": 800,
            "vote_average": 8.7,
            "video": false,
            "poster_path": "https://wallpapercave.com/dwp1x/wp11667632.png"
        },
        {
            "id": 10,
            "title": "Assassin's Creed Valhalla",
            "overview": "Assassin's Creed Valhalla is an action role-playing game developed and published by Ubisoft.",
            "original_title": "Assassin's Creed Valhalla",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdnb.artstation.com/p/assets/images/images/026/278/397/large/anupam-arts-assassiins-creed.jpg?1588349637",
            "popularity": 8.2,
            "vote_count": 750,
            "vote_average": 8.6,
            "video": false,
            "poster_path": "https://cdnb.artstation.com/p/assets/images/images/026/278/397/large/anupam-arts-assassiins-creed.jpg?1588349637"
        },
        {
            "id": 11,
            "title": "Call of Duty: Modern Warfare",
            "overview": "Call of Duty: Modern Warfare is a first-person shooter game published by Activision.",
            "original_title": "Call of Duty: Modern Warfare",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdnb.artstation.com/p/assets/images/images/030/578/431/large/artdrist-design-modern-warfare.jpg?1601020791",
            "popularity": 8.1,
            "vote_count": 700,
            "vote_average": 8.5,
            "video": false,
            "poster_path": "https://cdnb.artstation.com/p/assets/images/images/030/578/431/large/artdrist-design-modern-warfare.jpg?1601020791"
        },
        {
            "id": 12,
            "title": "Uncharted 4: A Thief's End",
            "overview": "Uncharted 4: A Thief's End is an action-adventure game developed by Naughty Dog.",
            "original_title": "Uncharted 4: A Thief's End",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdnb.artstation.com/p/assets/images/images/002/600/983/large/leandro-amaral-drake-portrait-portfolio.jpg?1463521663",
            "popularity": 8.0,
            "vote_count": 650,
            "vote_average": 8.8,
            "video": false,
            "poster_path": "https://cdnb.artstation.com/p/assets/images/images/002/600/983/large/leandro-amaral-drake-portrait-portfolio.jpg?1463521663"
        },
        {
            "id": 13,
            "title": "Pokémon Sword and Shield",
            "overview": "Pokémon Sword and Shield are role-playing video games developed by Game Freak and published by The Pokémon Company.",
            "original_title": "Pokémon Sword and Shield",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdna.artstation.com/p/assets/images/images/032/088/136/large/keane-ip-pokemon-journeys-the-legend-of-sword-shield-poster-5.jpg?1605451725",
            "popularity": 7.9,
            "vote_count": 600,
            "vote_average": 8.2,
            "video": false,
            "poster_path": "https://cdna.artstation.com/p/assets/images/images/032/088/136/large/keane-ip-pokemon-journeys-the-legend-of-sword-shield-poster-5.jpg?1605451725"
        },
        {
            "id": 14,
            "title": "Final Fantasy VII Remake",
            "overview": "Final Fantasy VII Remake is an action role-playing game developed and published by Square Enix.",
            "original_title": "Final Fantasy VII Remake",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png",
            "popularity": 7.8,
            "vote_count": 550,
            "vote_average": 8.7,
            "video": false,
            "poster_path": "https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png"
        },
        {
            "id": 15,
            "title": "Horizon Zero Dawn",
            "overview": "Horizon Zero Dawn is an action role-playing game developed by Guerrilla Games.",
            "original_title": "Horizon Zero Dawn",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://cdna.artstation.com/p/assets/images/images/024/138/208/large/guilherme-rocha-montagem-horizon-zero-dawn.jpg?1581438634",
            "popularity": 7.7,
            "vote_count": 500,
            "vote_average": 8.9,
            "video": false,
            "poster_path": "https://cdna.artstation.com/p/assets/images/images/024/138/208/large/guilherme-rocha-montagem-horizon-zero-dawn.jpg?1581438634"
        },
        {
            "id": 16,
            "title": "FIFA 22",
            "overview": "FIFA 22 is a football simulation video game published by EA Sports.",
            "original_title": "FIFA 22",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/88/d5/1c/88d51c761297d177b051f8cd078816c5.jpg",
            "popularity": 7.6,
            "vote_count": 450,
            "vote_average": 8.4,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/88/d5/1c/88d51c761297d177b051f8cd078816c5.jpg"
        },
        {
            "id": 17,
            "title": "The Elder Scrolls V: Skyrim",
            "overview": "The Elder Scrolls V: Skyrim is an action role-playing game developed by Bethesda Game Studios.",
            "original_title": "The Elder Scrolls V: Skyrim",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/3a/0f/34/3a0f3448351cbe9ac69632a656e7550a.jpg",
            "popularity": 7.5,
            "vote_count": 400,
            "vote_average": 8.8,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/3a/0f/34/3a0f3448351cbe9ac69632a656e7550a.jpg"
        },
        {
            "id": 18,
            "title": "BioShock Infinite",
            "overview": "BioShock Infinite is a first-person shooter game developed by Irrational Games.",
            "original_title": "BioShock Infinite",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/71/91/8d/71918d07010f57f9bae86898fc6a0d70.jpg",
            "popularity": 7.4,
            "vote_count": 350,
            "vote_average": 8.7,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/71/91/8d/71918d07010f57f9bae86898fc6a0d70.jpg"
        },
        {
            "id": 19,
            "title": "Gears 5",
            "overview": "Gears 5 is a third-person shooter game developed by The Coalition.",
            "original_title": "Gears 5",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/d0/a5/aa/d0a5aaa3a705affb8a40e2fc42017840.jpg",
            "popularity": 7.3,
            "vote_count": 300,
            "vote_average": 8.5,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/d0/a5/aa/d0a5aaa3a705affb8a40e2fc42017840.jpg"
        },
        {
            "id": 20,
            "title": "Destiny 2",
            "overview": "Destiny 2 is a free-to-play online-only multiplayer first-person shooter game developed by Bungie.",
            "original_title": "Destiny 2",
            "original_language": "en",
            "adult": false,
            "backdrop_path": "https://i.pinimg.com/564x/94/60/6a/94606a0c977b5bfb3ab4cc6f65be66f2.jpg",
            "popularity": 7.2,
            "vote_count": 250,
            "vote_average": 8.2,
            "video": false,
            "poster_path": "https://i.pinimg.com/564x/94/60/6a/94606a0c977b5bfb3ab4cc6f65be66f2.jpg"
        }
    ]
}

export default dummy